name: ESLint

on:
  push:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "🛸 install eslint html plugin"
        run: npm i eslint-plugin-html

      - name: "🔍 lint code"
        run: npx eslint . --report-unused-disable-directives
